topsection
Shy-006/cf pull request #1
Opened 2024-12-18 06:46 UTC by Shy-006

This pr introduces the top section of the clockify website
![Screenshot from 2024-12-18 12-11-31](https://github.com/user-attachments/assets/19d11835-55a1-4097-85db-9c190f454587)

2024-12-18 12:33 UTC, B-TAMILSELVAN commented
match the UI properly

2024-12-18 12:33 UTC, B-TAMILSELVAN requested changes

2024-12-18 12:33 UTC, B-TAMILSELVAN commented on index.css
>      background-color: #ddd;
save colors in css variables and use?
Apply at all places

2024-12-18 13:27 UTC, Shy-006 commented
> match the UI properly

ui matched

2024-12-18 13:59 UTC, Shy-006 commented on index.css
>      background-color: #ddd;
clors have been stored in variables

2024-12-18 14:00 UTC, Shy-006 commented
> match the UI properly

matched properly

2024-12-18 16:30 UTC, B-TAMILSELVAN commented
format the html and css file properly

2024-12-18 16:31 UTC, B-TAMILSELVAN commented
resolve the merge conflicts

2024-12-18 16:31 UTC, B-TAMILSELVAN requested changes

2024-12-18 16:31 UTC, B-TAMILSELVAN commented on index.css
> +--lightgreen:#4caf50;
format them properly

2024-12-18 16:31 UTC, B-TAMILSELVAN commented on index.css
> +    --Grey:rgba(144, 164, 174, 1);
follow naming convention properly when naming colors

2024-12-18 17:08 UTC, Shy-006 commented on index.css
> +    --Grey:rgba(144, 164, 174, 1);
naming convention have beeon followed

2024-12-18 17:08 UTC, Shy-006 commented on index.css
> +--lightgreen:#4caf50;
formatted

2024-12-19 05:41 UTC, B-TAMILSELVAN approved these changes

2024-12-19 05:43 UTC, merged